'use strict';

import StoreHelper from '../../lib/StoreHelper';

export const ITEMS_ACTION_TYPES = {
    LOCKS_FETCH: 'LOCKS_FETCH',
    LOCKS_FETCH_SUCCESS: 'LOCKS_FETCH_SUCCESS',
    LOCKS_FETCH_FAIL: 'LOCKS_FETCH_FAIL',
    LOCKS_CLEAR: 'LOCKS_CLEAR',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH_SUCCESS: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH_SUCCESS',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH_FAIL: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH_FAIL',
    LOCK_BRANCHES_ASSIGNMENTS_CLEAR: 'LOCK_BRANCHES_ASSIGNMENTS_CLEAR',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE_SUCCESS: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE_SUCCESS',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE_FAIL: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE_FAIL',
    UNLOCKERS_FETCH: 'UNLOCKERS_FETCH',
    UNLOCKERS_FETCH_SUCCESS: 'UNLOCKERS_FETCH_SUCCESS',
    UNLOCKERS_FETCH_FAIL: 'UNLOCKERS_FETCH_FAIL',
    UNLOCKERS_CLEAR: 'UNLOCKERS_CLEAR',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH_SUCCESS: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH_SUCCESS',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH_FAIL: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH_FAIL',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_CLEAR: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_CLEAR',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE_SUCCESS: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE_SUCCESS',
    UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE_FAIL: 'UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE_FAIL',
}
export const fetchLocks = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCKS_FETCH);

export const clearLocks = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCKS_CLEAR);

export const fetchLockBranchesAssignments = (lockId) => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_FETCH, lockId);

export const saveLockBranchesAssignments = (lockId, assignments) => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_SAVE, { lockId, assignments });

export const clearLockBranchesAssignments = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_CLEAR);

export const fetchUnlockers = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.UNLOCKERS_FETCH);

export const clearUnlockers = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.UNLOCKERS_CLEAR);

export const fetchUnlockerEmployeesAssignments = (type, id) => StoreHelper.createAction(ITEMS_ACTION_TYPES.UNLOCKER_EMPLOYEES_ASSIGNMENTS_FETCH, { type, id });

export const saveUnlockerEmployeesAssignments = (type, id, assignments) => StoreHelper.createAction(ITEMS_ACTION_TYPES.UNLOCKER_EMPLOYEES_ASSIGNMENTS_SAVE, { type, id, assignments });

export const clearUnlockerEmployeesAssignments = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.UNLOCKER_EMPLOYEES_ASSIGNMENTS_CLEAR);
