'use strict';

import StoreHelper from '../../lib/StoreHelper';

export const ITEMS_ACTION_TYPES = {
    /*
    COMBINATIONS_FETCH: 'COMBINATIONS_FETCH',
    COMBINATIONS_FETCH_SUCCESS: 'COMBINATIONS_FETCH_SUCCESS',
    COMBINATIONS_FETCH_FAIL: 'COMBINATIONS_FETCH_FAIL',
    KEYS_FETCH: 'KEYS_FETCH',
    KEYS_FETCH_SUCCESS: 'KEYS_FETCH_SUCCESS',
    KEYS_FETCH_FAIL: 'KEYS_FETCH_FAIL',
    KEYS_CLEAR: 'KEYS_CLEAR',
    KEY_TYPES_FETCH: 'KEY_TYPES_FETCH',
    KEY_TYPES_FETCH_SUCCESS: 'KEY_TYPES_FETCH_SUCCESS',
    KEY_TYPES_FETCH_FAIL: 'KEY_TYPES_FETCH_FAIL',
    KEY_TYPES_CLEAR: 'KEY_TYPES_CLEAR',
    */
    LOCKS_FETCH: 'LOCKS_FETCH',
    LOCKS_FETCH_SUCCESS: 'LOCKS_FETCH_SUCCESS',
    LOCKS_FETCH_FAIL: 'LOCKS_FETCH_FAIL',
    LOCKS_CLEAR: 'LOCKS_CLEAR',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH_SUCCESS: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH_SUCCESS',
    LOCK_BRANCHES_ASSIGNMENTS_FETCH_FAIL: 'LOCK_BRANCHES_ASSIGNMENTS_FETCH_FAIL',
    LOCK_BRANCHES_ASSIGNMENTS_CLEAR: 'LOCK_BRANCHES_ASSIGNMENTS_CLEAR',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE_SUCCESS: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE_SUCCESS',
    LOCK_BRANCHES_ASSIGNMENTS_SAVE_FAIL: 'LOCK_BRANCHES_ASSIGNMENTS_SAVE_FAIL'
}
export const fetchLocks = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCKS_FETCH);

export const clearLocks = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCKS_CLEAR);

export const fetchLockBranchesAssignments = (lockId) => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_FETCH, lockId);

export const saveLockBranchesAssignments = (lockId, assignments) => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_SAVE, { lockId, assignments });

export const clearLockBranchesAssignments = () => StoreHelper.createAction(ITEMS_ACTION_TYPES.LOCK_BRANCHES_ASSIGNMENTS_CLEAR);
